services:
  test:
    image: test
    container_name: test
    ports:
      - "0:8080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TEST_SECRET_1: "${TEST_SECRET_1}"
      TEST_SECRET_2: "${TEST_SECRET_2}"
